apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appname }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Values.appname }}
            servicePort: 80