apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appname }}
  name: {{ .Values.appname }}
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP